{% set version = "2.27.25" %}

package:
  name: types-requests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/types-requests/types-requests-{{ version }}.tar.gz
  sha256: 805ae7e38fd9d157153066dc4381cf585fd34dfa212f2fc1fece248c05aac571

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-urllib3 <1.27

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/requests-stubs/__init__.pyi  # [unix]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for requests
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
