{% set version = "2.30.0.0" %}

package:
  name: types-requests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/types-requests/types-requests-{{ version }}.tar.gz
  sha256: dec781054324a70ba64430ae9e62e7e9c8e4618c185a5cb3f87a6738251b5a31

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - types-urllib3 <1.27

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/requests-stubs/__init__.pyi  # [unix]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for requests
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
