{% set version = "2.28.11.12" %}

package:
  name: types-requests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/types-requests/types-requests-{{ version }}.tar.gz
  sha256: fd530aab3fc4f05ee36406af168f0836e6f00f1ee51a0b96b7311f82cb675230

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-urllib3 <1.27

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/requests-stubs/__init__.pyi  # [unix]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for requests
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
