{% set version = "2.28.11.9" %}

package:
  name: types-requests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/types-requests/types-requests-{{ version }}.tar.gz
  sha256: b942e832566810c4b521c2ae70c6cd990abd7f518e0c661d9a8d90a29b1cd19a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-urllib3 <1.27

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/requests-stubs/__init__.pyi  # [unix]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for requests
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
